### ISSUE TITLE
https://www.verschwörhaus.de/ redirects to http://www.verschwoerhaus.de

### ISSUE THREAD

**Issue by FelixWohlfrom** [verschwoerhaus/verschwoerhaus.de#10]
Any subpage of verschwörhaus.de, e.g. https://verschwörhaus.de/umzug will be forwarded without trailing slash in the tld.
This means, https://verschwörhaus.de/umzug will be forwarded to https://verschwoerhaus.deumzug.

**Comment by robbi5** [comment]
Thanks, fixed. The other domains (like the one with the umlaut) are not configured in this repo.
