### ISSUE TITLE
Mastodon-Account

### ISSUE THREAD

**Issue by Lukas2112** [verschwoerhaus/verschwoerhaus.de#7]
Would a Mastodon account on the instance of the State Commissioner for Data Protection and Freedom of Information of the State of Baden-Württemberg Bawü.social be considerable?

**Comment by jaqPi** [comment]
https://chaos.social/web/@verschwoerhaus

Ist erstellt, muss in der Fußzeile noch verlinkt werden.

**Comment by jaqPi** [comment]
Erledigt von @robbi5
